image: "node:lts-alpine"

before_script:
  - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .cache/
    - public/

pages:
  script:
    - mkdir public/ || true
    - npm run export -- --basepath $CI_PROJECT_NAME
    - cp -a __sapper__/export/$CI_PROJECT_NAME/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
